#line 1 "engines/director/lingo/lingo-lex.cpp"
/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#define YY_NO_UNISTD_H
#define FORBIDDEN_SYMBOL_EXCEPTION_FILE
#define FORBIDDEN_SYMBOL_EXCEPTION_fprintf
#define FORBIDDEN_SYMBOL_EXCEPTION_fwrite
#define FORBIDDEN_SYMBOL_EXCEPTION_fread
#define FORBIDDEN_SYMBOL_EXCEPTION_stdin
#define FORBIDDEN_SYMBOL_EXCEPTION_stdout
#define FORBIDDEN_SYMBOL_EXCEPTION_stderr
#define FORBIDDEN_SYMBOL_EXCEPTION_exit
#define FORBIDDEN_SYMBOL_EXCEPTION_getc

#include "common/str.h"

#include "director/director.h"
#include "director/lingo/lingo.h"
#include "director/lingo/lingo-ast.h"
#include "director/lingo/lingo-codegen.h"
#include "director/lingo/lingo-gr.h"
#include "director/lingo/lingo-the.h"

using namespace Director;

static const char *inputbuffer;
static uint inputlen;

#line 48 "engines/director/lingo/lingo-lex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[370] =
    {   0,
        0,    0,   93,   91,    1,   89,   89,   91,   91,   88,
       88,   88,   87,   88,   84,   88,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   91,    1,   85,   91,
        1,   89,    0,    0,   90,    2,   83,   86,   86,   87,
       82,   80,   81,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       25,   85,   27,   31,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   50,   51,   85,   53,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,

       85,   71,   85,   85,   85,   85,    1,    0,    0,   85,
        2,   86,   85,   85,    7,   85,   85,   85,   85,   85,
       85,   85,   85,   19,   85,   85,   85,   85,    0,    0,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   45,   85,   85,   48,   85,   85,   85,   85,   85,
       57,   85,   85,   85,   85,   62,   85,   85,   85,   85,
       85,   68,   85,   85,   85,   85,   85,   85,   85,    0,
       85,    5,   85,   85,    9,   12,   85,   15,   85,   17,
       18,    0,    0,   20,   85,   85,   85,    0,   85,   85,
       85,   30,   32,   34,   35,   37,   85,   85,   40,   85,

       85,   47,   85,   52,   54,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   67,   69,   70,   85,   85,
       85,   75,   77,   85,    0,   85,   85,    6,   85,   85,
       13,   85,   85,   19,   22,   23,   85,   25,   85,   85,
       85,   33,   36,   38,   85,   85,   41,   85,   46,   85,
       85,   85,   85,   85,   85,   85,   63,   64,   85,   85,
        0,    0,   73,   85,   85,   78,   79,    0,   85,    4,
        8,   85,   85,   16,   19,   24,   26,   85,   85,   39,
       85,   44,   49,   85,   85,   58,   59,   60,   85,   65,
       66,    0,    0,    0,   74,   76,    0,   85,   85,   10,

       85,   85,   85,   85,   85,   85,   85,    0,    0,    0,
        0,   21,   85,   11,   14,   28,   85,   42,   55,   56,
       85,    0,    0,    0,   21,   85,   85,   43,   85,    0,
        0,    0,    0,   85,   29,   85,    0,    0,    0,    0,
        3,   85,    0,    0,    0,    0,    0,    0,   85,    0,
        0,    0,    0,    0,   85,    0,    0,   85,    0,    0,
       85,   72,   85,   72,   72,   72,   85,   61,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    9,    1,    8,
        8,    8,    8,    8,    8,   10,    8,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    8,    1,   12,
       13,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       24,   31,   32,   33,   34,   35,   36,   37,   38,   24,
        8,    1,    8,    8,   24,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   24,   48,   49,   50,   51,
       52,   53,   24,   54,   55,   56,   57,   58,   59,   60,
       61,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   62,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   63,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    2,    3,    3,    2,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    2
    } ;

static const flex_int16_t yy_base[377] =
    {   0,
        0,   62,  545,  823,   66,  823,  823,  466,    0,  823,
      457,  434,   55,   59,  823,  425,   58,   56,   61,   62,
       59,   57,   63,   56,   98,    0,  101,  108,  109,  137,
      138,   74,  179,  181,  133,   64,  355,  130,  182,  243,
      212,  823,  239,  252,  823,    0,  823,  240,  178,   84,
      823,  823,  823,    0,  105,  103,  104,  119,  139,  143,
      148,  150,  158,  175,  186,  160,  196,  204,  211,  201,
      235,  212,    0,  212,  220,  210,  218,  220,  232,  227,
      239,  219,  226,  235,    0,    0,  233,    0,  249,  251,
      233,  254,  259,  239,  257,  257,  261,  281,  273,  281,

      275,    0,  285,  278,  281,  286,  334,  303,  124,  302,
        0,  166,  290,  304,    0,  297,  294,  299,  300,  312,
      322,  317,  327,  346,  319,  331,  331,  343,  358,  113,
      338,  331,  343,  339,  334,  350,  353,  340,  360,  339,
      355,    0,  356,  349,    0,  368,  360,  354,  364,  372,
        0,  385,  372,  384,  383,    0,  381,  385,  393,  387,
      393,  392,  404,  398,  401,  406,  408,  414,  419,  420,
      406,  425,  415,  420,  426,  421,  440,    0,  424,    0,
        0,  458,  111,    0,  441,  445,  450,  438,  437,  456,
      442,    0,  445,    0,  446,    0,  452,  463,  462,  455,

      467,    0,  468,    0,    0,  468,  473,  483,  466,  472,
      476,  472,  481,  475,  479,    0,    0,    0,  522,  494,
      489,  491,  487,  497,  497,  503,  498,    0,  515,  513,
        0,  516,  521,    0,    0,    0,  517,  823,  525,  518,
      515,    0,    0,    0,  517,  516,    0,  532,    0,  523,
      528,  528,  528,  537,  534,  538,    0,    0,  532,  544,
      576,  108,    0,  543,  555,    0,    0,  558,  558,  539,
        0,  575,  565,    0,    0,    0,    0,  577,  576,    0,
      578,    0,    0,  566,  571,    0,    0,    0,  578,    0,
        0,  579,  578,  588,    0,    0,  577,  575,  599,  585,

      588,  606,  612,  606,  602,  599,  626,  606,  611,  619,
      609,    0,  615,    0,    0,    0,  617,  619,    0,    0,
      620,  624,  622,  636,  823,  640,  629,    0,  630,  634,
      634,  653,  647,  660,    0,  661,  646,  686,  672,  655,
        0,  661,  665,  692,   82,  666,  668,  667,  668,  705,
      681,  672,  715,  717,  690,  692,  685,  697,  702,  732,
      707,  737,  711,    0,  739,   79,  712,    0,  823,  802,
       79,  804,  806,  810,  812,  817
    } ;

static const flex_int16_t yy_def[377] =
    {   0,
      369,    1,  369,  369,  369,  369,  369,  370,  371,  369,
      369,  369,  369,  369,  369,  369,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  369,  369,  372,  369,
      369,  369,  369,  370,  369,  373,  369,  369,  369,  369,
      369,  369,  369,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  369,  369,  369,  372,
      373,  369,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  369,  369,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  369,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  374,  369,  372,  372,  372,  372,  369,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  369,  372,  372,  372,  372,  372,
      372,  372,  372,  375,  372,  372,  372,  369,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      369,  369,  372,  372,  372,  372,  372,  369,  372,  372,
      372,  372,  372,  372,  375,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  369,  369,  369,  372,  372,  369,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  369,  369,  369,
      369,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  369,  369,  369,  369,  372,  372,  372,  372,  369,
      369,  369,  369,  372,  372,  372,  369,  369,  369,  369,
      372,  372,  369,  369,  369,  369,  369,  369,  372,  369,
      369,  369,  369,  369,  372,  369,  369,  372,  369,  369,
      372,  376,  372,  376,  376,  376,  372,  372,    0,  369,
      369,  369,  369,  369,  369,  369
    } ;

static const flex_int16_t yy_nxt[887] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   26,   26,   35,   36,   26,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   26,   26,   35,   36,
       26,    4,   37,   38,   49,   50,   38,   41,   42,   42,
       41,   51,   52,   55,   58,   59,   62,   56,   72,   68,
       63,   39,   60,   46,   65,   57,   66,   69,   70,   61,
       64,   71,   92,   49,   50,   67,  106,   55,   58,   59,

       62,   56,   72,   68,   63,   39,   60,   65,   57,   66,
       69,   70,   61,   64,   71,   76,   92,   73,   67,  106,
      113,  115,   79,   77,   40,   74,   80,   82,   43,   78,
       75,  107,   42,   42,  107,  114,   81,   83,  116,   76,
      365,   73,   84,  344,  113,  115,   79,   77,   74,  108,
       80,   82,   78,   75,  103,  104,   85,  118,  114,   81,
       83,  105,  116,   89,   86,   84,   87,   88,   90,  261,
      117,   91,  182,  108,  129,  119,  112,  124,  103,  104,
       85,  118,  120,  121,  105,  107,   89,   86,  112,   87,
       88,   90,  109,  117,   91,   93,  110,   94,  119,   99,

       95,  124,  100,  101,   68,  120,  121,   96,   97,  102,
      122,   98,   69,   41,   42,   42,   41,  123,  125,   93,
      110,   94,  126,   99,   95,  127,  100,  101,   68,  128,
       96,   97,  102,  122,   98,   69,  129,  131,  134,  129,
      123,  135,  125,  132,  133,  136,  126,  137,  138,  127,
       48,  147,  128,  139,  140,  144,  142,   45,  145,  141,
      131,  146,  134,  148,  135,  151,  132,  133,  136,  149,
      137,  156,  138,  143,   43,  147,  139,  140,  144,  150,
      142,  145,  141,  152,  146,  157,  153,  148,  151,  154,
      158,  159,  155,  149,  156,  160,  143,  130,  161,  162,

       41,  163,  150,  164,  107,  166,  152,  165,  157,  153,
      167,  168,  154,  158,  159,  155,  169,  170,  171,  160,
      172,  161,  173,  162,  163,  174,  175,  164,  166,  176,
      178,  165,  177,  167,  168,  107,   42,   42,  107,  169,
      179,  170,  171,  172,  180,  181,  173,  182,  174,  175,
      182,  184,  176,  108,  178,  177,  185,  186,  187,  129,
      189,  191,  129,  190,  179,  193,  194,  180,  195,  181,
      197,  192,  199,  196,  184,  198,  200,  108,  201,  185,
      186,  202,  187,  203,  189,  191,  190,  204,  193,  194,
      188,  205,  195,  197,  192,  199,  109,  196,  206,  198,

      200,  207,  201,  208,  202,  209,  210,  203,  183,  211,
      204,  212,  213,  188,  205,  214,   41,  215,  216,  217,
      130,  206,  218,  221,  207,  219,  220,  208,  209,  222,
      210,  223,  211,  224,  212,  213,  225,   53,  226,  214,
      215,  216,  217,  227,   48,  228,  218,  221,  219,  220,
      229,  230,  231,  222,  232,  223,  233,  224,  235,  182,
      225,  226,  182,  236,  237,   47,  238,  227,  228,  239,
      240,   45,  241,  229,  230,  231,  242,  243,  232,  233,
      244,  245,  235,  248,  246,  249,  250,  236,  237,  238,
      251,  252,  239,  247,  240,  241,  254,  253,  258,  242,

      243,  255,  256,  244,  257,  245,  248,  259,  246,  249,
      250,  260,  263,  265,  251,  252,  247,  264,  266,  254,
      183,  253,  258,  261,  255,  256,  261,  257,  267,  268,
      259,  269,  270,  271,  260,  272,  263,  265,  273,  274,
      264,  266,  276,  277,  369,  278,  279,  280,  281,  282,
      290,  267,  268,  283,  269,  270,  284,  271,  285,  272,
      286,  299,  273,  274,  287,  276,  288,  277,  278,  279,
      280,  281,  289,  282,  290,  291,  283,  261,  295,  284,
      261,  285,  296,  286,  262,  299,  297,  287,  298,  288,
      300,  369,  301,  302,  303,  289,  304,  308,  291,  305,

      292,  295,  293,  306,  307,  296,  309,  311,  294,  297,
      310,  298,  312,  313,  300,  301,  314,  302,  303,  315,
      304,  308,  305,  292,  316,  293,  306,  307,  317,  309,
      311,  294,  318,  319,  310,  312,  320,  313,  262,  314,
      321,  330,  315,  322,  323,  324,  325,  326,  316,  327,
      328,  329,  317,  332,  333,  318,  319,  331,  334,  320,
      335,  336,  337,  338,  321,  330,  322,  323,  324,  325,
      326,  339,  327,  328,  329,  340,  332,  341,  333,  342,
      331,  343,  334,  335,  336,  337,  338,  344,  348,  346,
      344,  349,  350,  344,  352,  339,  344,  353,  340,  354,

      355,  341,  356,  342,  343,  347,  344,  357,  358,  344,
      359,  348,  360,  346,  349,  350,  344,  352,  344,  344,
      353,  344,  354,  355,  351,  369,  356,  361,  347,  362,
      357,  369,  358,  344,  359,  360,  344,  363,  365,  367,
      365,  365,  368,  365,  369,  369,  369,  351,  345,  369,
      361,  369,  362,  369,  345,  369,  369,  369,  369,  369,
      363,  369,  367,  369,  369,  368,  369,  345,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  345,  369,  345,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  345,  369,  369,  369,  369,  366,

      369,  366,   44,   44,  369,   44,   44,   54,   54,  111,
      111,  234,  369,  369,  234,  275,  275,  364,  364,  369,
      364,  364,    3,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369
    } ;

static const flex_int16_t yy_chk[887] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,   13,   13,    2,    5,    5,    5,
        5,   14,   14,   17,   18,   19,   20,   17,   24,   22,
       20,    2,   19,  371,   21,   17,   21,   22,   23,   19,
       20,   23,   32,   50,   50,   21,   36,   17,   18,   19,

       20,   17,   24,   22,   20,    2,   19,   21,   17,   21,
       22,   23,   19,   20,   23,   27,   32,   25,   21,   36,
       55,   57,   28,   27,    2,   25,   28,   29,    5,   27,
       25,   38,   38,   38,   38,   56,   28,   29,   58,   27,
      366,   25,   29,  345,   55,   57,   28,   27,   25,   38,
       28,   29,   27,   25,   35,   35,   30,   60,   56,   28,
       29,   35,   58,   31,   30,   29,   30,   30,   31,  262,
       59,   31,  183,   38,  130,   61,  112,   66,   35,   35,
       30,   60,   62,   63,   35,  109,   31,   30,   49,   30,
       30,   31,   38,   59,   31,   33,   39,   33,   61,   34,

       33,   66,   34,   34,   39,   62,   63,   33,   33,   34,
       64,   33,   39,   41,   41,   41,   41,   65,   67,   33,
       39,   33,   68,   34,   33,   69,   34,   34,   39,   70,
       33,   33,   34,   64,   33,   39,   71,   72,   75,   71,
       65,   76,   67,   74,   74,   77,   68,   78,   79,   69,
       48,   87,   70,   80,   80,   82,   81,   44,   83,   80,
       72,   84,   75,   89,   76,   91,   74,   74,   77,   90,
       78,   94,   79,   81,   41,   87,   80,   80,   82,   90,
       81,   83,   80,   92,   84,   95,   92,   89,   91,   93,
       96,   97,   93,   90,   94,   98,   81,   71,   99,  100,

       43,  101,   90,  103,   40,  104,   92,  103,   95,   92,
      104,  105,   93,   96,   97,   93,  106,  108,  110,   98,
      113,   99,  114,  100,  101,  116,  117,  103,  104,  118,
      120,  103,  119,  104,  105,  107,  107,  107,  107,  106,
      121,  108,  110,  113,  122,  123,  114,  124,  116,  117,
      124,  125,  118,  107,  120,  119,  126,  127,  128,  129,
      131,  133,  129,  132,  121,  134,  135,  122,  136,  123,
      138,  133,  140,  137,  125,  139,  141,  107,  143,  126,
      127,  144,  128,  146,  131,  133,  132,  147,  134,  135,
      129,  148,  136,  138,  133,  140,  107,  137,  149,  139,

      141,  150,  143,  152,  144,  153,  154,  146,  124,  155,
      147,  157,  158,  129,  148,  159,   37,  160,  161,  162,
      129,  149,  163,  166,  150,  164,  165,  152,  153,  167,
      154,  168,  155,  169,  157,  158,  170,   16,  171,  159,
      160,  161,  162,  172,   12,  173,  163,  166,  164,  165,
      174,  175,  176,  167,  177,  168,  179,  169,  185,  182,
      170,  171,  182,  186,  187,   11,  188,  172,  173,  189,
      190,    8,  191,  174,  175,  176,  193,  195,  177,  179,
      197,  198,  185,  200,  199,  201,  203,  186,  187,  188,
      206,  207,  189,  199,  190,  191,  209,  208,  213,  193,

      195,  210,  211,  197,  212,  198,  200,  214,  199,  201,
      203,  215,  220,  222,  206,  207,  199,  221,  223,  209,
      182,  208,  213,  219,  210,  211,  219,  212,  224,  225,
      214,  226,  227,  229,  215,  230,  220,  222,  232,  233,
      221,  223,  237,  239,    3,  240,  241,  245,  246,  248,
      259,  224,  225,  250,  226,  227,  251,  229,  252,  230,
      253,  270,  232,  233,  254,  237,  255,  239,  240,  241,
      245,  246,  256,  248,  259,  260,  250,  261,  264,  251,
      261,  252,  265,  253,  219,  270,  268,  254,  269,  255,
      272,    0,  273,  278,  279,  256,  281,  292,  260,  284,

      261,  264,  261,  285,  289,  265,  293,  297,  261,  268,
      294,  269,  298,  299,  272,  273,  300,  278,  279,  301,
      281,  292,  284,  261,  302,  261,  285,  289,  303,  293,
      297,  261,  304,  305,  294,  298,  306,  299,  261,  300,
      307,  322,  301,  308,  309,  310,  311,  313,  302,  317,
      318,  321,  303,  323,  324,  304,  305,  322,  326,  306,
      327,  329,  330,  331,  307,  322,  308,  309,  310,  311,
      313,  332,  317,  318,  321,  333,  323,  334,  324,  336,
      322,  337,  326,  327,  329,  330,  331,  338,  340,  339,
      338,  342,  343,  344,  346,  332,  344,  347,  333,  348,

      349,  334,  351,  336,  337,  339,  350,  352,  355,  350,
      356,  340,  357,  339,  342,  343,  353,  346,  354,  353,
      347,  354,  348,  349,  344,    0,  351,  358,  339,  359,
      352,    0,  355,  360,  356,  357,  360,  361,  362,  363,
      365,  362,  367,  365,    0,    0,    0,  344,  338,    0,
      358,    0,  359,    0,  344,    0,    0,    0,    0,    0,
      361,    0,  363,    0,    0,  367,    0,  350,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  353,    0,  354,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  360,    0,    0,    0,    0,  362,

        0,  365,  370,  370,    0,  370,  370,  372,  372,  373,
      373,  374,    0,    0,  374,  375,  375,  376,  376,    0,
      376,  376,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "engines/director/lingo/lingo-lex.l"

#define YY_NO_INPUT 1
#line 59 "engines/director/lingo/lingo-lex.l"

// Push lines in stack
static void pushLine(uint num) {
	LingoCompiler *compiler = g_lingo->_compiler;

	if (num > inputlen)
		return;

	compiler->_lines[2] = compiler->_lines[1];
	compiler->_lines[1] = compiler->_lines[0];
	compiler->_lines[0] = &inputbuffer[num];
}

static void count() {
	LingoCompiler *compiler = g_lingo->_compiler;

	if (debugChannelSet(-1, kDebugParse))
		debug("LEXER: Read '%s' at %d:%d", yytext, compiler->_linenumber, compiler->_colnumber);

	char *p = yytext;

	while (*p) {
		if (*p == '\n') {
			compiler->_linenumber++;
			compiler->_colnumber = 0;
			pushLine(compiler->_bytenumber + 1);
		} else if (*p == '\xC2' && *(p + 1) == '\xAC') { // continuation
			compiler->_linenumber++;
			compiler->_colnumber = 0;
		} else {
			compiler->_colnumber++;
		}
		p++;
		compiler->_bytenumber++;
	}
}

static Common::String *cleanupString(const char *s) {
	Common::String *res = new Common::String;

	while (*s) {
		if (*s == '\xC2' && *(s + 1) == '\xAC') { // continuation
			s += 2;
			*res += ' '; // replace with space
			continue;
		}
		*res += *s;
		s++;
	}

	return res;
}

static void skipWhitespace(const char **ptr) {
	while (true) {
		if (**ptr == ' ' || **ptr == '\t') {
			*ptr += 1;
		} else if (**ptr == '\xC2' && *(*ptr + 1) == '\xAC') { // continuation
			*ptr += 2;
		} else {
			break;
		}
	}
}

static Common::String *readUntilWhitespace(const char **ptr) {
	Common::String *res = new Common::String;

	while (true) {
		if (**ptr == ' ' || **ptr == '\t') {
			break;
		}
		if (**ptr == '\xC2' && *(*ptr + 1) == '\xAC') { // continuation
			break;
		}
		*res += **ptr;
		*ptr += 1;
	}

	return res;
}

static Common::String *readUntilNewline(const char **ptr) {
	Common::String *res = new Common::String;

	while ((**ptr != '\n') && (**ptr != '\r') && (**ptr != '\0')) {
		if (**ptr == '\xC2' && *(*ptr + 1) == '\xAC') { // continuation
			*ptr += 2;
			*res += ' '; // replace with space
			continue;
		}
		*res += **ptr;
		*ptr += 1;
	}

	return res;
}

#line 907 "engines/director/lingo/lingo-lex.cpp"
#line 161 "engines/director/lingo/lingo-lex.l"
 /* At least one digit, so that a lone '.' is not a float. It sits ahead of
  * {operator} in the rules, so without this the dot operator could never win. */
#line 911 "engines/director/lingo/lingo-lex.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 172 "engines/director/lingo/lingo-lex.l"


#line 1132 "engines/director/lingo/lingo-lex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 370 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 369 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 174 "engines/director/lingo/lingo-lex.l"
{ count(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 176 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.s = new Common::String(yytext + 1); return tSYMBOL; }	// D3, skip '#'
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 178 "engines/director/lingo/lingo-lex.l"
{ count(); return tABBREVIATED; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 179 "engines/director/lingo/lingo-lex.l"
{ count(); return tABBREV; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 180 "engines/director/lingo/lingo-lex.l"
{ count(); return tABBR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 181 "engines/director/lingo/lingo-lex.l"
{ count(); return tAFTER; }		// D3
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 182 "engines/director/lingo/lingo-lex.l"
{ count(); return tAND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 183 "engines/director/lingo/lingo-lex.l"
{ count(); return tBEFORE; }	// D3
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 184 "engines/director/lingo/lingo-lex.l"
{ count(); return tCAST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 185 "engines/director/lingo/lingo-lex.l"
{ count(); return tCASTLIB; }	// D5
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 186 "engines/director/lingo/lingo-lex.l"
{ count(); return tCASTLIBS; }	// D5
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 187 "engines/director/lingo/lingo-lex.l"
{ count(); return tCHAR; }		// D3
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 188 "engines/director/lingo/lingo-lex.l"
{ count(); return tCHARS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 189 "engines/director/lingo/lingo-lex.l"
{ count(); return tCONTAINS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 190 "engines/director/lingo/lingo-lex.l"
{ count(); return tDATE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 191 "engines/director/lingo/lingo-lex.l"
{ count(); return tDELETE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 192 "engines/director/lingo/lingo-lex.l"
{ count(); return tDOWN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 193 "engines/director/lingo/lingo-lex.l"
{ count(); return tELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 194 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr = &yytext[3]; // Skip 'end '
		skipWhitespace(&ptr);

		if (!scumm_stricmp(ptr, "if"))
			return tENDIF;
		else if (!scumm_stricmp(ptr, "repeat"))
			return tENDREPEAT;
		else if (!scumm_stricmp(ptr, "tell"))
			return tENDTELL;

		yylval.s = new Common::String(ptr);

		return tENDCLAUSE;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 211 "engines/director/lingo/lingo-lex.l"
{ count(); return tEXIT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 212 "engines/director/lingo/lingo-lex.l"
{ count(); return tFACTORY; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 213 "engines/director/lingo/lingo-lex.l"
{ count(); return tFIELD; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 214 "engines/director/lingo/lingo-lex.l"
{ count(); return tFRAME; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 215 "engines/director/lingo/lingo-lex.l"
{ count(); return tGLOBAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 216 "engines/director/lingo/lingo-lex.l"
{ count(); return tGO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 217 "engines/director/lingo/lingo-lex.l"
{ count(); return tHILITE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "engines/director/lingo/lingo-lex.l"
{ count(); return tIF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 219 "engines/director/lingo/lingo-lex.l"
{ count(); return tINSTANCE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 220 "engines/director/lingo/lingo-lex.l"
{ count(); return tINTERSECTS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 221 "engines/director/lingo/lingo-lex.l"
{ count(); return tINTO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "engines/director/lingo/lingo-lex.l"
{ count(); return tIN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 223 "engines/director/lingo/lingo-lex.l"
{ count(); return tITEM; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 224 "engines/director/lingo/lingo-lex.l"
{ count(); return tITEMS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 225 "engines/director/lingo/lingo-lex.l"
{ count(); return tLAST; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 226 "engines/director/lingo/lingo-lex.l"
{ count(); return tLINE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 227 "engines/director/lingo/lingo-lex.l"
{ count(); return tLINES; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 228 "engines/director/lingo/lingo-lex.l"
{ count(); return tLONG; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 229 "engines/director/lingo/lingo-lex.l"
{ count(); return tMACRO; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 230 "engines/director/lingo/lingo-lex.l"
{ count(); return tMEMBER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 231 "engines/director/lingo/lingo-lex.l"
{ count(); return tMENU; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 232 "engines/director/lingo/lingo-lex.l"
{ count(); return tMENUS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 233 "engines/director/lingo/lingo-lex.l"
{ count(); return tMENUITEM;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 234 "engines/director/lingo/lingo-lex.l"
{ count(); return tMENUITEMS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 235 "engines/director/lingo/lingo-lex.l"
{ count(); return tMETHOD; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 236 "engines/director/lingo/lingo-lex.l"
{ count(); return tMOD;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 237 "engines/director/lingo/lingo-lex.l"
{ count(); return tMOVIE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 238 "engines/director/lingo/lingo-lex.l"
{ count(); return tNEXT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 239 "engines/director/lingo/lingo-lex.l"
{ count(); return tNOT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "engines/director/lingo/lingo-lex.l"
{ count(); return tNUMBER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 241 "engines/director/lingo/lingo-lex.l"
{ count(); return tOF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 242 "engines/director/lingo/lingo-lex.l"
{ count(); return tON; }		// D3
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 243 "engines/director/lingo/lingo-lex.l"
{ count(); return tOPEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "engines/director/lingo/lingo-lex.l"
{ count(); return tOR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "engines/director/lingo/lingo-lex.l"
{ count(); return tPLAY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "engines/director/lingo/lingo-lex.l"
{ count(); return tPREVIOUS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "engines/director/lingo/lingo-lex.l"
{ count(); return tPROPERTY; }	// D4
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "engines/director/lingo/lingo-lex.l"
{ count(); return tPUT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "engines/director/lingo/lingo-lex.l"
{ count(); return tREPEAT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "engines/director/lingo/lingo-lex.l"
{ count(); return tRETURN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "engines/director/lingo/lingo-lex.l"
{ count(); return tSCRIPT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "engines/director/lingo/lingo-lex.l"
{ count(); return tASSERTERROR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 253 "engines/director/lingo/lingo-lex.l"
{ count(); return tSET; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "engines/director/lingo/lingo-lex.l"
{ count(); return tSHORT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "engines/director/lingo/lingo-lex.l"
{ count(); return tSOUND; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 256 "engines/director/lingo/lingo-lex.l"
{ count(); return tSPRITE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 257 "engines/director/lingo/lingo-lex.l"
{ count(); return tSTARTS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 258 "engines/director/lingo/lingo-lex.l"
{ count(); return tTELL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 259 "engines/director/lingo/lingo-lex.l"
{ count(); return tTHE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 260 "engines/director/lingo/lingo-lex.l"
{ count(); return tTHEN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 261 "engines/director/lingo/lingo-lex.l"
{ count(); return tTIME; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 262 "engines/director/lingo/lingo-lex.l"
{ count(); return tTO; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 263 "engines/director/lingo/lingo-lex.l"
{
		count();

		const char *ptr =  &yytext[5]; // Skip 'when '
		skipWhitespace(&ptr);

		Common::String *eventName = readUntilWhitespace(&ptr);

		skipWhitespace(&ptr);
		ptr += 4; // Skip 'then'
		skipWhitespace(&ptr);

		Common::String *stmt = readUntilNewline(&ptr);

		yylval.w.eventName = eventName;
		yylval.w.stmt = stmt;
		return tWHEN;
	}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 281 "engines/director/lingo/lingo-lex.l"
{ count(); return tWHILE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 282 "engines/director/lingo/lingo-lex.l"
{ count(); return tWINDOW; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 283 "engines/director/lingo/lingo-lex.l"
{ count(); return tWITH; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 284 "engines/director/lingo/lingo-lex.l"
{ count(); return tWITHIN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 285 "engines/director/lingo/lingo-lex.l"
{ count(); return tWORD; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 286 "engines/director/lingo/lingo-lex.l"
{ count(); return tWORDS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 287 "engines/director/lingo/lingo-lex.l"
{ count(); return tXTRAS; } // D5
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 289 "engines/director/lingo/lingo-lex.l"
{ count(); return tNEQ; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 290 "engines/director/lingo/lingo-lex.l"
{ count(); return tGE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 291 "engines/director/lingo/lingo-lex.l"
{ count(); return tLE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 292 "engines/director/lingo/lingo-lex.l"
{ count(); return tCONCAT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 293 "engines/director/lingo/lingo-lex.l"
{ count(); return tEQ; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 295 "engines/director/lingo/lingo-lex.l"
{
		// The dot is part of the pattern because pre-D5 games put it inside
		// variable names -- C.H.A.O.S. Continuum has `a.1` and `a2.`, see
		// tests/varnames.lingo. From D5 on it is the property access operator,
		// so give everything from the first dot back to the scanner and let it
		// come round again as its own token. Before count(), so the line and
		// column counters only see what is actually consumed.
		if (g_director->getVersion() >= 500) {
			const char *dot = strchr(yytext, '.');
			if (dot)
				yyless(dot - yytext);
		}

		count();
		yylval.s = new Common::String(yytext);

		return tVARID;
	}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 313 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.f = atof(yytext); return tFLOAT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 314 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.i = strtol(yytext, NULL, 10); return tINT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 315 "engines/director/lingo/lingo-lex.l"
{ count(); return *yytext; }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 316 "engines/director/lingo/lingo-lex.l"
{ count(); return '\n'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 317 "engines/director/lingo/lingo-lex.l"
{ count(); yylval.s = cleanupString(&yytext[1]); yylval.s->deleteLastChar(); return tSTRING; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 318 "engines/director/lingo/lingo-lex.l"
{ count(); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 320 "engines/director/lingo/lingo-lex.l"
ECHO;
	YY_BREAK
#line 1697 "engines/director/lingo/lingo-lex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 370 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 370 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 369);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 320 "engines/director/lingo/lingo-lex.l"


extern int yydebug;

namespace Director {

int LingoCompiler::parse(const char *code) {
	inputbuffer = code;
	_bytenumber = 0;
	inputlen = strlen(code);

	_lines[0] = _lines[1] = _lines[2] = code;

	YY_BUFFER_STATE bp;

	if (debugChannelSet(-1, kDebugParse))
		yydebug = 1;
	else
		yydebug = 0;

	yy_delete_buffer(YY_CURRENT_BUFFER);

	bp = yy_scan_string(code);
	yy_switch_to_buffer(bp);
	yyparse();
	yy_delete_buffer(bp);

	return 0;
}

} // End of namespace Director

